insert into public.tags (name)
values
  ('gaming'),
  ('music'),
  ('movies'),
  ('travel'),
  ('fitness'),
  ('food'),
  ('sports'),
  ('anime'),
  ('books'),
  ('coding'),
  ('business'),
  ('study'),
  ('career'),
  ('technology'),
  ('photography'),
  ('art'),
  ('fashion'),
  ('cars'),
  ('language exchange'),
  ('friendship'),
  ('dating'),
  ('comedy'),
  ('news'),
  ('finance'),
  ('entrepreneurship'),
  ('startups'),
  ('ai'),
  ('culture'),
  ('cooking'),
  ('education')
on conflict (name) do nothing;